### ISSUE TITLE
“扫码”功能增强

### ISSUE THREAD

**Issue by eyelly-wu** [monako97/2fa-for-macOS#1]
### 原因
现目扫码是打开本地的图库，然后选取目标二维码图片后才能进行导入。
操作上多少是有点繁琐的，得准备好对应的二维码到图库中。
大部分场景可能用户的二维码不在图库里面，可能是在浏览器页面或者是存储在其他应用中的（例如我就是存储到备忘录中的）。

### 期望
希望可以直接扫描当前屏幕的二维码或者类似于鼠标截图识取图片一样的操作，这样便捷性又提升了一个台阶

**Comment by moneko-o** [comment]
> ### 原因
> 现目扫码是打开本地的图库，然后选取目标二维码图片后才能进行导入。 操作上多少是有点繁琐的，得准备好对应的二维码到图库中。 大部分场景可能用户的二维码不在图库里面，可能是在浏览器页面或者是存储在其他应用中的（例如我就是存储到备忘录中的）。
> 
> ### 期望
> 希望可以直接扫描当前屏幕的二维码或者类似于鼠标截图识取图片一样的操作，这样便捷性又提升了一个台阶

其实之前有做过这个功能, 但是需要更多的权限, 以及软件包将会变得更大, 同时添加新密码属于非常低频的操作, 于是就把该功能删除了;

目前可以将图片从电脑的任意位置拖动到程序中, 不需要特意从图库中选取二维码的;

**Comment by moneko-o** [comment]
> ### 原因
> 现目扫码是打开本地的图库，然后选取目标二维码图片后才能进行导入。 操作上多少是有点繁琐的，得准备好对应的二维码到图库中。 大部分场景可能用户的二维码不在图库里面，可能是在浏览器页面或者是存储在其他应用中的（例如我就是存储到备忘录中的）。
> 
> ### 期望
> 希望可以直接扫描当前屏幕的二维码或者类似于鼠标截图识取图片一样的操作，这样便捷性又提升了一个台阶

同时也支持直接将图片从浏览器或者其它窗口中拖入到状态栏图标、应用面板中

**Comment by eyelly-wu** [comment]
@monako97 能支持拖拽图片导入也是不错的，你不说我还真不知道可以这样。我刚测试了下，分别从备忘录和相册往“读取二维码”的位置进行拖拽，表现为
1. 备忘录拖拽
会出现**读取文件失败**的提示
![image](https://github.com/monako97/2fa-for-macOS/assets/24505069/b7117a1f-6450-4a46-828b-e127e328ee95)
2. 相册拖拽什么表现都没有
![image](https://github.com/monako97/2fa-for-macOS/assets/24505069/337c4e7c-597f-4fdb-931c-13b1ab363503)

通过相册选取对应的二维码图片是可以导入的，上述两种方式都不行

**Comment by moneko-o** [comment]
> @monako97 能支持拖拽图片导入也是不错的，你不说我还真不知道可以这样。我刚测试了下，分别从备忘录和相册往“读取二维码”的位置进行拖拽，表现为
> 
> 1. 备忘录拖拽
>    会出现**读取文件失败**的提示
>    ![image](https://private-user-images.githubusercontent.com/24505069/335941977-b7117a1f-6450-4a46-828b-e127e328ee95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTQwMzgsIm5iZiI6MTcxNzQ5MzczOCwicGF0aCI6Ii8yNDUwNTA2OS8zMzU5NDE5NzctYjcxMTdhMWYtNjQ1MC00YTQ2LTgyOGItZTEyN2UzMjhlZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MzUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ODZkNTQ1NDllMGZiNzRmZjQ5OTVjMTUyZGIxODNmZTJkNGZjMGYyNThhNzNjN2NjNWRmMTMyNGU5ZTcwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oYP3qEMqSVYF4qxMcV3fT446CrNhE0IEKhh3I260HXE)
> 2. 相册拖拽什么表现都没有
>    ![image](https://private-user-images.githubusercontent.com/24505069/335942075-337c4e7c-597f-4fdb-931c-13b1ab363503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTQwMzgsIm5iZiI6MTcxNzQ5MzczOCwicGF0aCI6Ii8yNDUwNTA2OS8zMzU5NDIwNzUtMzM3YzRlN2MtNTk3Zi00ZmRiLTkzMWMtMTNiMWFiMzYzNTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MzUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2M2Q3OTI0MGU4OGVhODM3ZWYxMTYxY2UwZTlhZDc5OTY3MzczYTBiZjMyZWYxNWE0ZGEyNDVmYzA5NTY1ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GsAS7BVu4EZ6r60FVO-aEp_EVbovMY5UrPFLrUFN24o)
> 
> 通过相册选取对应的二维码图片是可以导入的，上述两种方式都不行

下个版本修复
