### ISSUE TITLE
增加图标

### ISSUE THREAD

**Issue by eyelly-wu** [monako97/2fa-for-macOS#2]
希望可以增加如下应用的图标

* https://v2ex.com/
* https://www.npmjs.com/
* https://hub.docker.com/

**Comment by moneko-o** [comment]
> 希望可以增加如下应用的图标
> 
> * https://v2ex.com/
> * https://www.npmjs.com/
> * https://hub.docker.com/

已在 1.21 添加 v2ex、docke 应用图标

npmjs的应用图标一直是存在的
